### ISSUE TITLE
Large asteroids split into smaller asteroids when hit

### ISSUE THREAD

**Issue by johnthagen** [johnthagen/rust-belt#63]

**Comment by mcdenhoed** [comment]
Might make some subtasks for this. I think an initial step would be to see if we can make the draw method take a slice instead of an array. Then we can more transparently have different numbers of vertices in broken up asteroids.

**Comment by johnthagen** [comment]
Sounds good to me!

**Comment by johnthagen** [comment]
I'm using milestone 1.1 for the next minor release.

**Comment by mcdenhoed** [comment]
So, things needed:

- [X] #124 : allow asteroids with different numbers of vertices (implemented in #125)
- [ ] #126 : allow creation of asteroids upon asteroid destruction (specify position, speed, rotation, rotation speed)
- [ ] #127 : allow using an asteroid's shape for a new asteroid. I think if we can make this one work, it will look very cool. (Also requires #128)

**Comment by mcdenhoed** [comment]
See the [split](https://github.com/johnthagen/rust-belt/tree/split) branch.

@johnthagen I've done an initial implementation of most of these features in there. Not perfect yet, but it sort of works.

**Comment by mcdenhoed** [comment]
Implemented in #130
